<?php
$gtm_id = Mage::getStoreConfig('google/gtmdatalayer/gtm_container_tag');
$optimize_yesno = Mage::getStoreConfig('google/gtmdatalayer/optimize_yesno');
$activity_scroll = (!Mage::getStoreConfig('google/cookie_consent/activity_scroll')) ? 0 : Mage::getStoreConfig('google/cookie_consent/activity_scroll');
# Cookie Consent Options
$cookie_consent = array(
    "enable" => Mage::getStoreConfig('google/cookie_consent/enable_cookie_consent'),
    "layout" => array(
        "position" => Mage::getStoreConfig('google/cookie_consent/position'),
        "layout" => Mage::getStoreConfig('google/cookie_consent/layout'),
        "color" => array(
            "banner" => Mage::getStoreConfig('google/cookie_consent/color_banner'),
            "button" => Mage::getStoreConfig('google/cookie_consent/color_button'),
            "banner_text" => Mage::getStoreConfig('google/cookie_consent/color_banner_text'),
            "button_text" => Mage::getStoreConfig('google/cookie_consent/color_button_text')
        ),
    ),
    "more_link" => $this->getBaseUrl().Mage::getStoreConfig('google/cookie_consent/more_link'),
    "compliance_type" => Mage::getStoreConfig('google/cookie_consent/compliance_type'),
    "activity_scroll" => Mage::getStoreConfig('google/cookie_consent/activity_scroll'),
    "activity_scroll_element" => Mage::getStoreConfig('google/cookie_consent/activity_scroll_element'),
    "activity_click" => Mage::getStoreConfig('google/cookie_consent/activity_click'),
    "deletecookies" => Mage::getStoreConfig('google/cookie_consent/deletecookies'),
    "userdefined_enable_functions" => Mage::getStoreConfig('google/cookie_consent/userdefined_enable_functions'),
    "text" => array(
        "message" => Mage::getStoreConfig('google/cookie_consent/text_message'),
        "button_dismiss" => Mage::getStoreConfig('google/cookie_consent/button_dismiss_text'),
        "button_deny" => Mage::getStoreConfig('google/cookie_consent/button_deny_text'),
        "button_accept" => Mage::getStoreConfig('google/cookie_consent/button_accept_text'),
        "policy_link" => Mage::getStoreConfig('google/cookie_consent/policy_link_text')
    ),

);

$usercentrics = array(
        "enable_usercentrics_consent" => Mage::getStoreConfig('google/cookie_consent/enable_usercentrics_consent'),
        "usercentrics_id" => Mage::getStoreConfig('google/cookie_consent/usercentrics_id')
);
?>
<style>
    .async-hide {
        opacity: 0 !important
    }

</style>
<?php if ($cookie_consent["enable"]): ?>
    <style>
        .cc-window.cc-banner{
            z-index:999999999;
        }
    </style>
    <script>
        function enableTracking(){
            localStorage.setItem('allowtracking', 'true');
            <?php if ($optimize_yesno) : ?>
            loadOptimizeTag("<?php echo $gtm_id ?>");
            <?php endif; ?>
            loadTagManager("<?php echo $gtm_id ?>");
            document.addEventListener('DOMContentLoaded', function() {
                <?php echo $cookie_consent["userdefined_enable_functions"]; ?>
            }, false);

        }
        function deleteCookies(){
            <?php echo $cookie_consent["deletecookies"]; ?>
            setTimeout(function(){ window.location.reload(true) }, 100);
            alert("All cookies deleted");
        }
        function changeCookieOnUserActivity(){
            <?php if(!$trigger=$cookie_consent["activity_scroll"]): ?>
            var activity = 0;
            var trigger = 0;
            <?php else: ?>
            var activity = 1;
            var trigger = <?php echo $trigger; ?>
            <?php endif; ?>

                document.addEventListener('DOMContentLoaded', function() {
                    <?php  if(!$selector = $cookie_consent['activity_scroll_element']):?>
                    var selector = 0;
                    <?php else: ?>
                    var selector = "<?php echo $selector; ?>";
                    <?php endif; ?>

                    if(selector){
                        scrolling(document.querySelector(selector),trigger,activity);
                    } else {
                        scrolling(window,trigger,activity);
                    }
                }, false);
        }
    </script>
    <script>
        var consent_status = getCookie("cookieconsent_status");
        var compliance_type = "<?php echo $cookie_consent["compliance_type"]; ?>";
    </script>
    <script>
        window.addEventListener("load", function () {
            window.cookieconsent.initialise({
                "palette": {
                    "popup": {
                        "background": "<?php echo $cookie_consent["layout"]["color"]["banner"]; ?>",
                        "text": "<?php echo $cookie_consent["layout"]["color"]["banner_text"]; ?>"
                    },
                    "button": {
                        "background": "transparent",
                        "text": "<?php echo $cookie_consent["layout"]["color"]["button_text"]; ?>",
                        "border": "<?php echo $cookie_consent["layout"]["color"]["button"]; ?>"
                    }
                },
                "position": "<?php echo $cookie_consent["layout"]["position"]; ?>",
                "type": "<?php echo $cookie_consent["compliance_type"]; ?>",
                "content": {
                    "message": "<?php echo $cookie_consent["text"]["message"]; ?>",
                    "dismiss": "<?php echo $cookie_consent["text"]["button_dismiss"]; ?>",
                    "deny": "<?php echo $cookie_consent["text"]["button_deny"]; ?>",
                    "allow": "<?php echo $cookie_consent["text"]["button_accept"]; ?>",
                    "link": "<?php echo $cookie_consent["text"]["policy_link"]; ?>",
                    "href": "<?php echo $cookie_consent["more_link"]; ?>"
                },
                onInitialise: function (status) {
                    var type = this.options.type;
                    var didConsent = this.hasConsented();
                    var consent_status = getCookie("cookieconsent_status");
                    if (type == 'opt-in' && didConsent) {
                        enableTracking();
                    }
                    if (type == 'opt-out' && consent_status!="deny") {
                        enableTracking();
                    }
                },

                onStatusChange: function(status, chosenBefore) {
                    var type = this.options.type;
                    var didConsent = this.hasConsented();
                    if (type == 'opt-in' && didConsent) {
                        enableTracking();
                    }
                    if (type == 'opt-out' && !didConsent) {
                        // disable cookies
                        deleteCookies();
                    }
                },

                onRevokeChoice: function() {
                    var type = this.options.type;
                    if (type == 'opt-in') {
                        deleteCookies()
                    }
                    if (type == 'opt-out') {
                        deleteCookies()
                    }
                },
            })
        });
        // Opt-Out Tracking
        if(compliance_type=="opt-out"){
            if(consent_status!="deny")
                enableTracking();
        }
    </script>
    <script>
        changeCookieOnUserActivity();
    </script>
<?php elseif ($usercentrics["enable_usercentrics_consent"]): ?>
    <script type="application/javascript" src="https://app.usercentrics.eu/latest/main.js" id="<?php echo $usercentrics["usercentrics_id"] ?>"> </script>
    <!-- Google Tag Manager -->
    <script type="text/plain" data-usercentrics="Google Tag Manager">(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','<?php echo $gtm_id; ?>');</script>
    <!-- End Google Tag Manager -->

<?php else: //cookie_consent["enable"]  ?>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','<?php echo $gtm_id; ?>');</script>
    <!-- End Google Tag Manager -->
<?php endif; //cookie_consent["enable"]  ?>
